config/routes.rb
Ihr::Application.routes.draw do
  resources :employees

  get "ihr/index"

  match 'accounts'      => 'users'
  match 'register', :to => 'users#new'
  match 'login',    :to => 'user_sessions#new'
  match 'logout',   :to => 'user_sessions#destroy'
  match 'test',     :to => 'ihr#test'

  resources :user_sessions, :users

  root :to => 'ihr#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :login, :email, :password, :password_confirmation, :openid_identifier
  validates_presence_of     :login, :directory_server
  validates_uniqueness_of   :login
  validates_confirmation_of :password

#  acts_as_authentic :validate_password_field => false
  acts_as_authentic do |c|
        c.logged_in_timeout = 1.minutes # for available options see documentation in: Authlogic::ActsAsAuthentic
  end
  
  protected
    def valid_ldap_credentials?(password_plaintext)
      # try to authenticate against the LDAP server
      ldap = Net::LDAP.new
      ldap.host = LDAP_HOST
      # first create the username/password strings to send to the LDAP server
      # add the domain so it looks like COMPANY\firstname.lastname
      ldap.auth "#{LDAP_DOMAIN}\\" + self.login, password_plaintext
      ldap.bind # will return false if authentication is NOT successful
    end
    
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  # configuration here, see documentation for sub modules of Authlogic::Session
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper :all
  helper_method :current_user_session, :current_user

  private
    def current_user_session
      return @current_user_session if defined?(@current_user_session)
      @current_user_session = UserSession.find
    end

    def current_user
      return @current_user if defined?(@current_user)
      @current_user = current_user_session && current_user_session.user
    end

    def require_user
      unless current_user
        store_location
        flash[:notice] = "You must be logged in to access this page"
        redirect_to new_user_session_url
        return false
      end
    end

    def require_no_user
      if current_user
        store_location
        flash[:notice] = "You must be logged out to access this page"
        redirect_to account_url
        return false
      end
    end

    def store_location
      session[:return_to] = request.request_uri
    end

    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end
  
end

app/controllers/ihr_controller.rb
class IhrController < ApplicationController
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy

  def new
    @user_session = UserSession.new
  end    

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash.now[:notice] = "Login successful!"
      redirect_to root_url
    else
      flash.now[:notice] = "Invalid login information, please try again!"
      render :action => :new
    end
  end    

  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default new_user_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => [:show, :edit, :update]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Account registered!"
#      redirect_back_or_default root_url
        redirect_to root_url 
      else
        render :action => :new
    end
  end
  
  def show
    @user = @current_user
  end

  def edit
    @user = @current_user
  end
  
  def remind
    flash[:notice] = "Please contact your system administrator!"
  end
    
  def update
    @user = @current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to root_url
    else
      render :action => :edit
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ihr_helper.rb
module IhrHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ihr/index.html.erb
<h1>Welcome to IHiS HR Portal</h1>
<p>Login Please or Sign Up</p>

app/views/layouts/application.html.erb
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->    
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
  <%= stylesheet_link_tag 'application', :media => 'screen' %>
  <%= formtastic_stylesheet_link_tag %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div id="top-menu">
	  <div id="account">
		<% if current_user %>
		  <%= link_to "My Profile", users_path %> |
		  <%= link_to "Logout", logout_path %>
		<% else %>
	      <%= link_to "Register", register_path %> |
	      <%= link_to "Login", login_path %>
	  	<% end %>
	  </div>
	</div>
	<div id="header">
	  <h1>iHR Portal</h1>
	</div>
	<div id="tabsD">
		<ul>
			 <!-- CSS Tabs -->
			 <li><a href="Profile.html"><span>Profile</span></a></li>
			 <li><a href="Products.html"><span>Leave</span></a></li>
			 <li id="current"><a href="Services.html"><span>Services</span></a></li>
			 <li><a href="Support.html"><span>Claim</span></a></li>
			 <li><a href="Order.html"><span>Performance</span></a></li>
			 <li><a href="News.html"><span>Reports</span></a></li>
		</ul>
	</div>
	<div id="container">
		<div id="leftsidebar">
			<ul>
				<li><%= link_to root_url %></li>
				<li><%= link_to users_path %></li>
				<li><%= link_to employees_path %></li>
			</ul>
		</div>
	    <div id="mainpage">
			<%= content_tag :h2, yield(:title) if show_title? %>
			<% flash.each do |name, msg| %>
		      <%= content_tag :div, msg, :id => "flash_#{name}" %>
		    <% end %>
			<%= yield %>
		</div>
	</div>
	<div id="footer">
	    Maintained by Ong Leong Seng (Part-Time Programmer), IHiS Pte Ltd&copy; 2010
	</div>
</body>
</html>

app/views/user_sessions/new.html.erb
<% title "Login" %>
<fieldset>
	<legend>Enter Your Login Details</legend>
	<% form_for :user_session do |f| %>
		<%= f.error_messages %>
		<div class="form_row">
			<%= f.label :login %>
			<%= f.text_field :login %>
		</div>
		<br />
		<div class="form_row">
			<%= f.label :password %>
			<%= f.password_field :password %>
		</div>
		<br />
		<div class="form_row">
			<%= f.check_box :remember_me %><%= f.label :remember_me %><br />
		</div>
		<br />
		<%= f.submit "Login" %>
	<% end %>
</fieldset>

<p>  
  Forgot your screen name or password? 
  <%= link_to "Remind Me!", :controller => "users", :action => "new" %>
</p>

<p>  
  Not registered yet?  <%= link_to "Register now!", register_path %>
</p>

app/views/users/edit.html.erb
<% title "Edit My Account" %>

<fieldset>
	<legend>Update user details</legend>
    <%= render :partial => "form" %>
</fieldset>

<br /><%= link_to "My Profile", edit_user_path %>

app/views/users/new.html.erb
<% title "Registration" %>

<fieldset>
	<legend>Register new or against an Active Directory</legend>
    <%= render :partial => "form" %>
</fieldset>

app/views/users/show.html.erb
<% title "User Details" %>
<p>
  <b>Login:</b>
  <%=h @user.login %>
</p>

<p>
  <b>Login count:</b>
  <%=h @user.login_count %>
</p>

<p>
  <b>Last request at:</b>
  <%=h @user.last_request_at %>
</p>

<p>
  <b>Last login at:</b>
  <%=h @user.last_login_at %>
</p>

<p>
  <b>Current login at:</b>
  <%=h @user.current_login_at %>
</p>

<p>
  <b>Last login ip:</b>
  <%=h @user.last_login_ip %>
</p>

<p>
  <b>Current login ip:</b>
  <%=h @user.current_login_ip %>
</p>


<%= link_to 'Edit', users_path %>